### ISSUE TITLE
[Feature] option to display popup on the side

### ISSUE THREAD

**Issue by DmitryEfimenko** [Maluen/code-medium#2]
First of all, thanks for an amazing extension!

I often find it useful to be able to see the article I'm editing while creating the gist. Currently, the popup is positioned in the middle of the screen and overlays the majority of the content. There could be an option to move the popup in the empty area of the page (to the left or to the right of the content) and make sure that the content of the article is still selectable. This way I'd be able to copy-paste things from the article into the gist.

**Comment by DmitryEfimenko** [comment]
I played a bit with CSS. You can achieve the desired behavior by applying the following CSS:

```css
.code-medium-extension-app {
  top: 5%;
  right: 0;
  left: 65%;
}

.code-medium-extension-app-iframe {
  position: absolute;
  right: 0;
  top: 0;
  left: 0;
  height: 90%;
}
```
